---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(conflicted)
library(cowplot)
knitr::opts_chunk$set(echo = TRUE)
filter <- dplyr::filter
ggsave <- cowplot::ggsave
```

```{r}
setwd('~/Documents/fels_git_repository_Fels_Bioinformatics_Meetup/week6/')
```

```{r}
# plot normal curve
ggplot(data = tibble(x = c(-3, 3)), aes(x)) +
  stat_function(fun = dnorm, n = 101, args = list(mean = 0, sd = 1)) +
  scale_y_continuous(name = "", breaks = NULL)

#ggsave('normal_curve.png', width = 4, height = 4)
ggsave('normal_curve2.png', width = 4, height = 3)
```

```{r}
# standard deviation example
ggplot(data = tibble(x = c(-3, 3)), aes(x)) +
  stat_function(fun = dnorm, n = 101, args = list(mean = 0, sd = 1)) +
  stat_function(fun = dnorm, n = 101, args = list(mean = 0, sd = 0.5), color = 'red') +
  stat_function(fun = dnorm, n = 101, args = list(mean = 0, sd = 2), color = 'darkblue') +
  scale_y_continuous(name = "", breaks = NULL)

#ggsave('vary_sd.png', width = 4, height = 3)
```

```{r}
# first option to highlight significant areas on the normal curve
ggplot(data = tibble(x = c(-3, 3)), aes(x)) +
  stat_function(fun = dnorm, n = 101, args = list(mean = 0, sd = 1)) +
  stat_function(fun = dnorm, geom = 'area', fill = 'gray', alpha = 0.3, 
                args = list(mean = 0, sd = 1), xlim = c(2, 3)) +
  geom_vline(xintercept = 2, linetype = 'dashed', color = "red", size = 0.5) + 
  stat_function(fun = dnorm, geom = 'area', fill = 'gray', alpha = 0.3, 
                args = list(mean = 0, sd = 1), xlim = c(-3, -2)) +
  geom_vline(xintercept = -2, linetype = 'dashed', color = "red", size = 0.5) + 
  scale_y_continuous(name = "", breaks = NULL) 


#ggsave('sig_areas_norm_curve.png', width = 4, height = 3)
```

```{r}
# better highlighting significant areas on the normal curve with just red
ggplot(data = tibble(x = c(-3, 3)), aes(x)) +
  stat_function(fun = dnorm, n = 101, args = list(mean = 0, sd = 1)) +
  stat_function(fun = dnorm, geom = 'area', fill = 'red', alpha = 0.8,  
                args = list(mean = 0, sd = 1), xlim = c(2, 3)) +
  stat_function(fun = dnorm, geom = 'area', fill = 'red', alpha = 0.8,
                args = list(mean = 0, sd = 1), xlim = c(-3, -2)) +
  scale_y_continuous(name = "", breaks = NULL) 


#ggsave('sig_areas_norm_curve2.png', width = 4, height = 3)
```

```{r}
# plot chi-square curve
ggplot(data = tibble(x = c(0, 20)), aes(x)) +
  stat_function(fun = dchisq, args = list(df = 4)) +
  scale_y_continuous(name = "", breaks = NULL)

#ggsave('chi_square.png', width = 4, height = 3)
```

```{r}
# plot chi-square curve with signficant areas highlighted in red
ggplot(data = tibble(x = c(0, 20)), aes(x)) +
  stat_function(fun = dchisq, args = list(df = 4)) +
  stat_function(fun = dchisq, geom = 'area', fill = 'red', alpha = 0.8,
                args = list(df = 4), xlim = c(11.070, 20)) +
  stat_function(fun = dchisq, geom = 'area', fill = 'red', alpha = 0.8,
                args = list(df = 4), xlim = c(0, 0.484)) +
  scale_y_continuous(name = "", breaks = NULL)

#ggsave('chi_sq_sig_areas.png', width = 4, height = 3)
```

```{r}
# make toy data for a chi square test
birth_days <- tibble(day = c('Sunday', 'Monday', 'Tuesday', 'Wednesday', 
                             'Thursday', 'Friday', 'Saturday'), 
                     num_births = c(33, 41, 63, 63, 47, 56, 47), 
                     num_days = c(rep(52, 5), 53, 52), 
                     exp_prob_birth = c(rep((52 / 365), 5), (53 / 365), (52 / 365)))
birth_days

chisq.test(birth_days$num_births, p = birth_days$exp_prob_birth)
```

```{r}
# code for multiple testing correction example
p_values <- c(0.05, 0.1, 0.008, 0.06, 0.15, 0.03, 0.09, 0.001, 0.01, 0.02)
```

```{r}
tibble(raw_pvalue = runif(1000, 0, 0.05)) %>% 
  mutate(holm = p.adjust(raw_pvalue), 
         fdr = p.adjust(raw_pvalue, method = 'fdr'),
         bonf = p.adjust(raw_pvalue, method = 'bonferroni'),
         bh = p.adjust(raw_pvalue, method = 'BH')) -> plot_p_values

plot_p_values %>% gather(method, adj_pvalue, holm:bh) %>%
  ggplot(aes(x = raw_pvalue, y = adj_pvalue, color = method)) + geom_point(alpha = 0.2)

plot_p_values %>% gather(method, adj_pvalue, holm:bh) %>%
  filter(method != 'fdr') %>%
  ggplot(aes(x = raw_pvalue, y = adj_pvalue, color = method)) + geom_line()
```

```{r}
# simulate coin tosses
num_heads <- rbinom(10, 10, 0.5)
>num_heads

num_heads_100 <- rbinom(100, 10, 0.5)
num_heads_100
```